### ISSUE TITLE
ceil function fails to parse correctly 

### ISSUE THREAD

**Issue by markhats** [fkleon/math-expressions#10]
The ceil function is failing to parse properly. This is because when the parser gets to the 'e' in ceil it recognises it as TokenType.EFUNC. This then messes up the subsequent parsing. This issue will occur with all functions containing the 'e' character. 

I guess it perhaps needs to check varBuffer or something before deciding to create the EFUNC token.

Code in question is around: https://github.com/fkleon/math-expressions/blob/325cf793e01aca3d7362121f4c796efbc2c0f2c1/lib/src/parser.dart#L196

**Comment by tanish2k09** [comment]
It's been a while. I'm using math_expressions for a certain calculator I'm working on and I read this TODO note going through the code. This seems like it would make a nice addition and I'm interested in implementing it but I'd need some time to understand the structure of the library.

**Comment by fkleon** [comment]
Hi @tanish2k09 - thanks for offering to take this on.

If you're still interested I suggest you have a look at my previous comment here which outlines the parser implementation: https://github.com/fkleon/math-expressions/pull/1#issuecomment-30180856

I'm not averse to a completely rewrite of the lexer/parser using a suitable library instead of the home-grown current solution. But I'd be equally happy with a small fix to the existing code base for this particular issue.

**Comment by tanish2k09** [comment]
> Hi @tanish2k09 - thanks for offering to take this on.
> 
> If you're still interested I suggest you have a look at my previous comment here which outlines the parser implementation: [#1 (comment)](https://github.com/fkleon/math-expressions/pull/1#issuecomment-30180856)
> 
> I'm not averse to a completely rewrite of the lexer/parser using a suitable library instead of the home-grown current solution. But I'd be equally happy with a small fix to the existing code base for this particular issue.

I think the best course of action would be to try to “port” over a reliable and well-established lib from one of the other languages like (Swift? C++?)

**Comment by tanish2k09** [comment]
Unless of course an edit is preferred over a rewrite

**Comment by fkleon** [comment]
Porting a specific library is one option, another one would be to switch to a grammar-based parsing approach to build the internal expression structure, e.g. via [dart-petitparser](https://github.com/petitparser/dart-petitparser#using-the-expression-builder).

I don't have a strong preference either way as to rewrite vs. fix. The advantage of the current shunting yard algorithm is that it's a classic and well understood algorithm, which is easy to implement. In `math_expressions`, it's just not very well implemented around handling ambiguity correctly, which can probably be fixed relatively easily, e.g. by prioritising longer tokens when trying to match function names.

That said, I've been wanting to explore grammar-based parsing, but haven't really gotten around to doing the research - merely due to a lack of time. There seems to be plenty of literature available that could be used as a reference, for example: [A Step-by-Step Solution Methodology for Mathematical Expressions](https://doi.org/10.3390/sym10070285).

I'd say pick whatever approach interests you most given the time you want to spend on this.

I've added a failing test case in 2241566fb82aef307186b42312d69b7351703708 a while ago, which might be useful for a fix.
