### ISSUE TITLE
How to handle percentage?

### ISSUE THREAD

**Issue by ghprod** [fkleon/math-expressions#28]
Hi,

Thanks for the package :+1: 

My question is how to handle percentage?

Example `50 - 10%`. 

The expected result is `45`.

But what I got is an exception.

```
RangeError (index): Invalid value: Valid value range is empty: -1

Parser.parse (package:math_expressions/src/parser.dart:50:28)
```

Sample code

```dart
    Parser p = Parser();

    Expression exp = p.parse('50 - 10%');

    print(exp.evaluate(EvaluationType.REAL, ContextModel()));
```

Thanks

**Comment by fkleon** [comment]
Hi @ghprod, this notation is not supported.

I suggest you rewrite the expression to use decimal notation instead of percentages.  
In your example, you could use one of the following equivalent expressions:

* ![50\cdot0.9](https://render.githubusercontent.com/render/math?math=50%5Ccdot0.9) 

```dart
Expression exp = p.parse('50 * 0.9');
```

* ![50-(50\cdot0.1)](https://render.githubusercontent.com/render/math?math=50-%2850%5Ccdot0.1%29)

```dart
Expression exp = p.parse('50 - (50 * 0.1)');
```

**Comment by ghprod** [comment]
Hi @fkleon 

Thank you for your suggestion. I'll try to rewrite it :+1:

**Comment by Ruwasoft** [comment]
Hi, Can you please explain me how you solved this issue ?
