### ISSUE TITLE
calc not right: 7x1.15 = 8.049999999999999999?

### ISSUE THREAD

**Issue by cnmade** [fkleon/math-expressions#63]
with the math_expressions library, we type
```
7*1.15
```
the calc result was
```
8.0499999999999
```

why it not return 8.05

**Comment by fkleon** [comment]
Hi @cnmade, check out #51 and my answer which I believe describes the same issue.

**Comment by cnmade** [comment]
thanks, i will try

**Comment by fkleon** [comment]
@cnmade You need to select the precision based on your appliation's requirements. I assume in your case you'd want a low(e) precision- maybe  of 3 significant digits - so that the result is rounded correctly:

```dart
void main() {
    double i = 7.0 * 1.15;
    print(i.toStringAsFixed(3)); # prints 8.05
}
```

Note that the original result `8.049999999999999 `only has 16 digits precision, so when asking for 19 significant digits you're getting a more precise (longer) value as per Dart's implementation of 64 bit double-precision floating point numbers.

Hope that helps!

**Comment by runoob-coder** [comment]
https://pub.dev/packages/decimal
