### ISSUE TITLE
derive is inaccurate

### ISSUE THREAD

**Issue by NedjmeDjedouani** [fkleon/math-expressions#65]
**the steps to reproduce**
Parser p =Parser();
Expression exp = p.parse("x^2");
exp.derive('x');   // (e({(2.0 * ln(x))}) * ((2.0 * (1.0 / x)) + (0.0 * ln(x))))
exp.derive('x').simplify()  // ((x^2.0) * (2.0 * (1.0 / x)))

**Expected output**
2*x

**Comment by fkleon** [comment]
Hi @NedjmeDjedouani 

If I'm not missing anything the result you describe is accurate, because `((x^2.0) * (2.0 * (1.0 / x)))` can be easily simplified to `2*x` (at least by a human) like so:

```
((x^2.0) * (2.0 * (1.0 / x)))
= (x^2.0) * (2.0 / x)
= (x*x) * (2.0 / x)
= (2*x*x) / x
= 2*x
```
The issue here is that the `simplify` function isn't smart enough to perform those simplification steps.

Would you agree with that?

**Comment by NedjmeDjedouani** [comment]
@fkleon yes after seeing simplify again it's giving the correct output i thought it's smart enough to perform all the simplification steps anyway & i was confused because of the derive func's complex output (exponential & logarithm)
 Going to close the issue thanks
